var githubHeader = {
    avatar_url:             "https://avatars.githubusercontent.com/u/104002967?v=4",
    created_at:             "2022-04-19T11:19:23Z",
    html_url:               "https://github.com/mortensokhode",
    name:                   "Mortenso Kodehode",
    public_repos:           10,
    repos_url:              "https://api.github.com/users/mortensokhode/repos",
    updated_at:             "2022-06-10T09:12:09Z",
    
    events_url:             "https://api.github.com/users/mortensokhode/events{/privacy}",
    followers_url:          "https://api.github.com/users/mortensokhode/followers",
    following:               1,
    following_url:          "https://api.github.com/users/mortensokhode/following{/other_user}",
    gists_url:              "https://api.github.com/users/mortensokhode/gists{/gist_id}",
    url:                    "https://api.github.com/users/mortensokhode",
    received_events_url:    "https://api.github.com/users/mortensokhode/received_events",
    starred_url:            "https://api.github.com/users/mortensokhode/starred{/owner}{/repo}",
    organizations_url:      "https://api.github.com/users/mortensokhode/orgs",
    subscriptions_url:      "https://api.github.com/users/mortensokhode/subscriptions",
    login:                  "mortensokhode",
    type:                   "User",
    twitter_username:       null,
    bio:                    null,
    blog:                   "",
    company:                null,
    email:                  null,
    followers:              0,
    gravatar_id:            "",
    hireable:               null,
    id:                     104002967,
    location:               null,
    node_id:                "U_kgDOBjL1lw",
    public_gists:           0,
    site_admin:             false,
    linkedInURL:            "https://www.linkedin.com/in/morten-s%C3%B8rreime-9310b36/"
}


const headerArray = ['avatar_url',
                     'created_at',
                     'html_url',
                     'name',
                     'public_rep',
                     'repos_url',
                     'updated_at']